name = "Stressify"
uuid = "8a229381-d7eb-4865-a507-cf9af2c5cd1e"
authors = ["Jo√£o Martins Filho <joaomfilho1995@gmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
CSV = "0.10.15"
Coverage = "1.6.1"
DataFrames = "1.7.0"
HTTP = "1.10.10"
JSON = "0.21.4"
Plots = "1.40.9"
Printf = "1.11.0"
Random = "1.11.0"
Statistics = "1.11.1"
Test = "1.11.0"

[extras]
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"

[targets]
test = ["Coverage"]
